# Generated by Django 2.2 on 2020-09-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_escape_room_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.AddField(
            model_name='theme',
            name='timer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
