# Generated by Django 2.2 on 2020-09-27 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_escape_room_app', '0002_auto_20200926_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Not Started', max_length=255)),
                ('timer', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('players', models.ManyToManyField(related_name='player_game', to='virtual_escape_room_app.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('hint', models.CharField(max_length=255)),
                ('story', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Puzzles',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='player',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='status',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='timer',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_theme', to='virtual_escape_room_app.Theme'),
        ),
        migrations.AddField(
            model_name='game',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_game', to='virtual_escape_room_app.Theme'),
        ),
    ]
